const router=require('express').Router();
const auth=require('../middleware/auth');
const role=require('../middleware/role');
const c=require('../controllers/users.controller');
router.get('/',auth,role('admin'),c.getAll);
router.post('/',auth,role('admin'),c.create);
router.put('/:id',auth,role('admin'),c.update);
router.patch('/:id/statut',auth,role('admin'),c.toggleActif);
router.delete('/:id',auth,role('admin'),c.remove);
module.exports=router;
